config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :movies, only: [:index, :show] do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_movie, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list if @list
    @bookmark.movie = @movie if @movie
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find_by(id: params[:list_id])
  end

  def set_movie
    @movie = Movie.find_by(id: params[:movie_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
require 'rest-client'

class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = List.all
    # @movies = Movie.order(:id).limit(20)
    @now_playing = fetch_movies('now_playing')
    @top_rated = fetch_movies('top_rated')
    @upcoming = fetch_movies('upcoming')
    @bookmark = Bookmark.new
    @list = List.new
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def fetch_movies(category)
    token = ENV['ACCESS_TOKEN']
    url = URI("https://api.themoviedb.org/3/movie/#{category}?language=en-US&page=1")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["accept"] = 'application/json'
    request["Authorization"] = "Bearer #{token}"

    response = http.request(request)
    data = JSON.parse(response.read_body)

    base_poster_url = "https://image.tmdb.org/t/p/w500"
    movies = []

    data["results"].each do |movie_hash|
      movie = Movie.find_by(title: movie_hash['title'])

      if movie
        movie.update(
          title: movie_hash['title'],
          overview: movie_hash['overview'],
          poster_url: "#{base_poster_url}#{movie_hash['poster_path']}",
          rating: movie_hash['vote_average'].to_f
        )
      else
        movie = Movie.create(
          title: movie_hash['title'],
          overview: movie_hash['overview'],
          poster_url: "#{base_poster_url}#{movie_hash['poster_path']}",
          rating: movie_hash['vote_average'].to_f
        )
      end

      movies << movie
    end

    movies
  end




  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name,:photo)
  end
end

app/controllers/movies_controller.rb
require 'rest-client'

class MoviesController < ApplicationController
  def index
    @movies = Movie.all.order(:id)
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR overview ILIKE :query"
      @movies = @movies.where(sql_subquery, query: "%#{params[:query]}%")
    end
    @bookmark = Bookmark.new
  end

  def show
    @movie = Movie.find(params[:id])
    @movies = Movie.where.not(id: @movie.id).order(:id).limit(20)
    @popular = fetch_movies('now_playing')
    @bookmark = Bookmark.new
  end

  private

  def fetch_movies(category)
  token = ENV['ACCESS_TOKEN']
  url = URI("https://api.themoviedb.org/3/movie/#{category}?language=en-US&page=1")

  http = Net::HTTP.new(url.host, url.port)
  http.use_ssl = true

  request = Net::HTTP::Get.new(url)
  request["accept"] = 'application/json'
  request["Authorization"] = "Bearer #{token}"

  response = http.request(request)
  data = JSON.parse(response.read_body)

  base_poster_url = "https://image.tmdb.org/t/p/w500"
  movies = []

  data["results"].each do |movie_hash|
    movie = Movie.find_by(title: movie_hash['title'])

    if movie
      movie.update(
        title: movie_hash['title'],
        overview: movie_hash['overview'],
        poster_url: "#{base_poster_url}#{movie_hash['poster_path']}",
        rating: movie_hash['vote_average'].to_f
      )
    else
      movie = Movie.create(
        title: movie_hash['title'],
        overview: movie_hash['overview'],
        poster_url: "#{base_poster_url}#{movie_hash['poster_path']}",
        rating: movie_hash['vote_average'].to_f
      )
    end

    movies << movie
  end

  movies
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/_form.html.erb
<% if @list %>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment, placeholder: 'Leave a comment' %>
    <%= f.association :movie, collection: Movie.where.not(id: @list.movies).order(:title), include_blank: false, input_html: { class: 'select2' } %>
    <%= f.submit 'Add', class: 'btn btn-flat' %>
  <% end %>
<% elsif @movie %>
  <%= simple_form_for [@movie, @bookmark], url: movie_bookmarks_path(@movie) do |f| %>
    <%= f.input :comment, placeholder: 'Leave a comment' %>
    <%= f.association :list, collection: List.where.not(id: @movie.lists).order(:name), include_blank: false, input_html: { class: 'select2' } %>
    <%= f.submit 'Add', class: 'btn btn-flat' %>
  <% end %>
<% end %>

app/views/bookmarks/_modal_show.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add <%= @movie.title %> to list</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for [@movie, @bookmark], url: movie_bookmarks_path(@movie) do |f| %>
        <div class="modal-body">
          <%= f.input :comment, placeholder: 'Leave a comment' %>
          <%= f.association :list, collection: List.where.not(id: @movie.lists).order(:name), include_blank: false, input_html: { class: 'select2' } %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Add', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="container ">
  <%= link_to 'Watchlists', lists_path, class: "m-3 btn btn-flat" %>
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3"  >
      <div class="bg-white rounded p-3 shadow">
        <% if @list %>
          <h3>Movie to <%= @list.name %></h3>
        <% elsif @movie %>
          <h3><%= @movie.title %> to List</h3>
        <% end %>
        <%= render 'bookmarks/form' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lists/_modal.html.erb
<div class="modal fade" id="listModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Create a New List</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for @list do |f| %>
        <div class="modal-body">
          <%= f.input :name, placeholder: 'Pick a list name' %>
          <%= f.input :photo, as: :file %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Add', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/_movies.html.erb
<%= link_to movie_path(movie), class:"text-decoration-none" do %>
  <li class="movie-card" >
    <div class="movie-card-category" data-aos="zoom-in" style="background-image: url(<%= movie.poster_url%>)">
    </div>
  <% end %>
  <div class="bookmark-button">
    <i class="fa-regular fa-bookmark fa-xl btn" style="color: white;" data-bs-toggle="modal" data-bs-target="#exampleModal<%=movie.id%>"></i>
  </div>
</li>
<%= render "bookmarks/modal", movie: movie, bookmark: @bookmark %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <h1>Make your own movie watchlist!</h1>
    <button type="button" class="btn btn-flat mt-3" data-bs-toggle="modal" data-bs-target="#listModal">
      Create a movie list
    </button>
  </div>
</div>
<div class="home-container">
  <h2 style="color: white;">Your Movie Watchlists</h2>
  <ul class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class:"text-decoration-none" do %>
        <li class="card" >
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1683758933/bsruv2qxr7kvxs6vzhir.jpg"%>)">
            <h3 class="card-title"><%= list.name %></h3>
          </div>
        <% end %>
        <div class="delete-button">
          <%= link_to list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this movie?" }, class: 'text-right flex-shrink-0' do %>
            <i class="fa-solid fa-trash-can" style="color: white;"></i>
          <% end %>
        </div>
      </li>
    <% end %>
    <li class="card">
      <div class="card-category" style="background-color: dark">
        <div class="add-button" >
          <i class="fa-solid fa-circle-plus fa-2xl" style="color: white;"  data-bs-toggle="modal" data-bs-target="#listModal"></i>
        </div>
      </div>
    </li>
  </ul>
  <div class="d-flex text-white align-items-center text-center list-title">
    <h2>Now Playing</h2>
    <%= link_to 'Explore All>', movies_path, class:"text-decoration-none movies-link"%>
  </div>
  <ul class="cards">
    <% @now_playing.each do |movie| %>
      <%= render "movies", movie: movie%>
    <% end %>
  </ul>
  <div class="d-flex text-white align-items-center text-center list-title">
    <h2>Top Rated</h2>
    <%= link_to 'Explore All>', movies_path, class:"text-decoration-none movies-link"%>
  </div>
  <ul class="cards">
    <% @top_rated.each do |movie| %>
      <%= render "movies", movie: movie%>
    <% end %>
  </ul>
  <div class="d-flex text-white align-items-center text-center list-title">
    <h2>Upcoming</h2>
    <%= link_to 'Explore All>', movies_path, class:"text-decoration-none movies-link"%>
  </div>
  <ul class="cards">
    <% @upcoming.each do |movie| %>
      <%= render "movies", movie: movie%>
    <% end %>
  </ul>
  <%= render "modal", list: @list %>
</div>

app/views/lists/new.html.erb
<div class="container ">
   <%= link_to 'Watchlists', lists_path, class: "m-3 btn btn-flat" %>
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3"  >
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Watchlist name' %>
            <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="home-container">
  <div class="content-wrap">
    <div class="buttons d-flex justify-content-between">
      <%= link_to 'Go Back', lists_path, class: "m-3 btn btn-flat" %>
      <div class="add-button align-self-center mr-3">
        <%= link_to  movies_path do %>
          <i class="fa-solid fa-circle-plus fa-2xl" style="color: #f5c518"></i>
        <% end %>
      </div>
    </div>
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div class="cards-show">
      <% @list.movies.each do |movie| %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="card-show">
          <%= link_to movie_path(movie), class:"text-decoration-none" do %>
            <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
            <div class="p-2 rounded-bottom d-flex flex-column">
              <strong><span class="text-muted font-weight-normal"> <i class="fas fa-star star-yellow"></i> <%= movie.rating %> </span></strong>
              <strong class="text-white"><%= movie.title %> </strong>
              <div class="d-flex align-items-end justify-content-between pt-4">
                <div>
                  <i class="fa-solid fa-quote-left" style="color: white"></i> <small class="flex-grow-1 text-muted">  <%= bookmark.comment %></small>
                </div>
              </div>
            </div>
          <% end %>
          <div class="delete-button">
            <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this movie?" }, class: 'text-right flex-shrink-0' do %>
              <i class="fa-solid fa-trash-can fa-xl" style="color: white;"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/movies/_carousel.html.erb
<div class="d-flex text-white align-items-center text-center mt-3 list-title">
  <h2>Popular Movies</h2>
  <%= link_to 'Explore All>', movies_path, class:"text-decoration-none movies-link"%>
</div>
<ul class="cards">
  <% @movies.each do |movie| %>
    <%= link_to movie_path(movie), class:"text-decoration-none" do %>
      <li class="movie-show-card" >
        <div class="movie-card-category" data-aos="zoom-in" style="background-image: url(<%= movie.poster_url%>)">
        </div>
      <% end %>
      <div class="bookmark-button">
        <i class="fa-regular fa-bookmark fa-xl btn" style="color: white;" data-bs-toggle="modal" data-bs-target="#exampleModal<%=movie.id%>"></i>
      </div>
    </li>
    <%= render "bookmarks/modal", movie: movie, bookmark: @bookmark %>
  <% end %>
</ul>

app/views/movies/index.html.erb
<div class="home-container">
  <div class="row justify-content-center mt-3">
    <div class="col-sm-8 my-3">
      <%= form_with url: movies_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div id="movies" class="cards-show">
      <% if @movies.any? %>
        <% @movies.each do |movie| %>
          <div class="card-show">
            <%= link_to movie_path(movie), class:"text-decoration-none" do %>
              <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
              <div class="p-2 rounded-bottom d-flex flex-column">
                <strong><span class="text-muted font-weight-normal"> <i class="fas fa-star star-yellow"></i> <%= movie.rating %> </span></strong>
                <strong class="text-white"><%= movie.title %> </strong>
              </div>
            <% end %>
            <div class="bookmark-button">
              <i class="fa-regular fa-bookmark fa-xl btn" style="color: white;" data-bs-toggle="modal" data-bs-target="#exampleModal<%=movie.id%>"></i>
            </div>
          </div>
          <%= render "bookmarks/modal", movie: movie, bookmark: @bookmark %>
        <% end %>
      <% else %>
        <em>Sorry, no movies found.</em>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="text-white movie-show-container">
  <div class="d-flex justify-content-between">
    <%= link_to 'Lists', lists_path, class: "m-3 btn btn-flat" %>
  </div>
  <div class="movie-show">
    <div class="movie-show-img">
      <%= image_tag @movie.poster_url, alt: @movie.title, class: "movie-img-show rounded-top" %>
    </div>
    <div class="movie-info">
      <h1><%= @movie.title %></h1>
      <p><i class="fas fa-star star-yellow"></i> <%= @movie.rating %></p>
      <div class="overview">
        <p class="overview-title">Overview</p>
        <p><%= @movie.overview %></p>
        <button type="button" class="btn btn-flat mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Add a movie
        </button>
      </div>
    </div>
  </div>
  <%= render 'carousel' %>
</div>
<%= render "bookmarks/modal_show" %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <div class="content-wrap">
    <h1>Make your own movie watchlist!</h1>
    <p> “Cinema is not only about making people dream. It's about changing things and making people think.”</p>
      <%= link_to 'My Watchlists', lists_path, class: "m-3 btn btn-flat" %>
   </div>
</div>
  </div>

    <div class="footer position-absolute bottom-0 start-0" >
  <div class="footer-links">
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-github" ></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-github" ></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.instagram.com/p/CjWVC7KKGED/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-film fa-xl" style="color: white;"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Movies", movies_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1683758933/bsruv2qxr7kvxs6vzhir.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
          </div>
        </li>
        <%# else %>
        <!--li class="nav-item"-->
        <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>